graph TD
    classDef red fill:#ff0000,stroke:#ff0000,color:#dfdfdf;
    classDef green fill:#00ff00,stroke:#00ff00,color:#202020;

    A((A))-->B((B));
    A-->C((C));
    B-->E((E));
    E-->F((F));
    E-->G((G));
    E-->H((H));

    class B,E red;
    class A,C,F,G,H green;
